In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model

In [2]:
mydata = pd.read_csv('stpsf-data/WFI/wim_zernikes_cycle9.csv', sep=',', header=0)
print(mydata.values)

[[ 1.00000e+00  4.80000e-01  1.00000e+00 ...  5.50217e-03 -9.46813e-03
   4.25296e-03]
 [ 1.00000e+00  4.80000e-01  2.00000e+00 ...  5.94724e-03 -9.23025e-03
   2.63345e-03]
 [ 1.00000e+00  4.80000e-01  3.00000e+00 ...  6.37167e-03 -9.13213e-03
   2.42618e-03]
 ...
 [ 1.80000e+01  2.30000e+00  3.00000e+00 ...  1.38555e-03 -1.68853e-03
   3.14048e-04]
 [ 1.80000e+01  2.30000e+00  4.00000e+00 ...  1.19143e-03 -2.00779e-03
   4.95551e-04]
 [ 1.80000e+01  2.30000e+00  5.00000e+00 ...  1.38649e-03 -1.88375e-03
   3.41620e-04]]


In [3]:
wavelength = mydata['wavelength']
mask1 = np.where(wavelength == 0.48)
mask2 = np.where(wavelength == 0.62)

In [4]:
mask1

(array([   0,    1,    2,    3,    4,  105,  106,  107,  108,  109,  210,
         211,  212,  213,  214,  315,  316,  317,  318,  319,  420,  421,
         422,  423,  424,  525,  526,  527,  528,  529,  630,  631,  632,
         633,  634,  735,  736,  737,  738,  739,  840,  841,  842,  843,
         844,  945,  946,  947,  948,  949, 1050, 1051, 1052, 1053, 1054,
        1155, 1156, 1157, 1158, 1159, 1260, 1261, 1262, 1263, 1264, 1365,
        1366, 1367, 1368, 1369, 1470, 1471, 1472, 1473, 1474, 1575, 1576,
        1577, 1578, 1579, 1680, 1681, 1682, 1683, 1684, 1785, 1786, 1787,
        1788, 1789]),)

In [5]:
localAngleX = mydata['axis_local_angle_x']
localAngleY = mydata['axis_local_angle_y']
globalX = mydata['global_x']
globalY = mydata['global_y']
#sca = mydata['sca']

In [6]:
localAngleXArray = np.array(localAngleX)[mask1]
localAngleYArray = np.array(localAngleY)[mask1]
globalXArray = np.array(globalX)[mask1]
globalYArray = np.array(globalY)[mask1]

In [7]:
angleInput = np.dstack((localAngleXArray, localAngleYArray))
poly = PolynomialFeatures(degree=4)
angleInput_ = poly.fit_transform(angleInput[0])
modelX = linear_model.LinearRegression()
modelY = linear_model.LinearRegression()
modelX.fit(angleInput_, globalXArray)
modelY.fit(angleInput_, globalYArray)

LinearRegression()

In [8]:
poly.powers_

array([[0, 0],
       [1, 0],
       [0, 1],
       [2, 0],
       [1, 1],
       [0, 2],
       [3, 0],
       [2, 1],
       [1, 2],
       [0, 3],
       [4, 0],
       [3, 1],
       [2, 2],
       [1, 3],
       [0, 4]])

In [9]:
poly.powers_[:,0]

array([0, 1, 0, 2, 1, 0, 3, 2, 1, 0, 4, 3, 2, 1, 0])

In [10]:
modelX.coef_

array([ 0.00000000e+00,  3.26517163e+02, -7.91139524e-02, -1.44166674e-01,
        1.52538813e+01,  9.54352387e-03,  1.57610407e+01, -3.94184908e-02,
        1.64559167e+01,  1.14887060e-02,  2.68675768e-02,  1.66020231e+00,
       -8.68491438e-02,  1.13539168e+00, -3.71086055e-01])

In [11]:
modelY.coef_

array([ 0.00000000e+00, -3.89361265e-04, -3.33968073e+02, -7.61333266e+00,
        1.27156584e-01, -2.32051981e+01,  1.02788877e-03, -1.64045687e+01,
        4.04509362e-02, -1.69721904e+01, -3.23316881e-01,  5.82181852e-02,
       -2.13256150e+00, -2.44781926e-01, -2.58474827e+00])

In [12]:
localAngleXArray = np.array(localAngleX)[mask2]
localAngleYArray = np.array(localAngleY)[mask2]
globalXArray = np.array(globalX)[mask2]
globalYArray = np.array(globalY)[mask2]

In [13]:
angleInput = np.dstack((localAngleXArray, localAngleYArray))
poly = PolynomialFeatures(degree=4)
angleInput_ = poly.fit_transform(angleInput[0])
modelX = linear_model.LinearRegression()
modelY = linear_model.LinearRegression()
modelX.fit(angleInput_, globalXArray)
modelY.fit(angleInput_, globalYArray)

LinearRegression()

In [14]:
modelX.coef_

array([ 0.00000000e+00,  3.26524734e+02, -7.93184474e-02, -1.42533388e-01,
        1.52540161e+01,  9.15045326e-03,  1.57607648e+01, -4.32651975e-02,
        1.64564495e+01,  2.66899516e-02,  2.06440395e-02,  1.66743464e+00,
       -9.07515177e-02,  1.11796961e+00, -4.09524478e-01])

In [15]:
modelY.coef_

array([ 0.00000000e+00, -4.01049469e-04, -3.33975734e+02, -7.61300133e+00,
        1.27326689e-01, -2.32048132e+01,  9.74243612e-04, -1.64039459e+01,
        4.12584128e-02, -1.69687836e+01, -3.28836010e-01,  5.75633969e-02,
       -2.11400026e+00, -2.46064702e-01, -2.62018071e+00])

In [16]:
def evalJ(jacobian, polyorder, x,y):
    evalArray = np.array([x,y])
    return np.sum(jacobian*np.prod(np.power(np.array(evalArray), polyorder), axis = 3), axis = 2)

def computeJacobian(wavelength, polyorder = 4, tolerance = 1e-4):
    #Read Input csv from STSCi Files 
    mydata = pd.read_csv('stpsf-data/WFI/wim_zernikes_cycle9.csv', sep=',', header=0)

    #Define mask to desired wavelength
    mask1 = np.where(mydata['wavelength']==wavelength)

    #Read columns from csv
    localAngleX = mydata['axis_local_angle_x']
    localAngleY = mydata['axis_local_angle_y']
    globalX = mydata['global_x']
    globalY = mydata['global_y']

    #Mask columns at desired wavelength
    localAngleXArray = np.array(localAngleX)[mask1]
    localAngleYArray = np.array(localAngleY)[mask1]
    globalXArray = np.array(globalX)[mask1]
    globalYArray = np.array(globalY)[mask1]

    
    #Sklearn multivariable polynomial fit
    angleInput = np.dstack((localAngleXArray, localAngleYArray))
    poly = PolynomialFeatures(degree=polyorder)
    angleInput_ = poly.fit_transform(angleInput[0])
    modelX = linear_model.LinearRegression()
    modelY = linear_model.LinearRegression()
    modelX.fit(angleInput_, globalXArray)
    modelY.fit(angleInput_, globalYArray)

    rx = modelX.score(angleInput_, globalXArray)
    ry = modelY.score(angleInput_, globalYArray)
    print("rx,ry =", rx, ry)
    if 1-rx>tolerance or 1-ry>tolerance:
        raise Exception("Not able to find a good model fit, please try again with higher polynomial order")

    coefX = modelX.coef_
    coefY = modelY.coef_
    xpowers = poly.powers_[:,0]
    ypowers = poly.powers_[:,1]
    newpowersx = np.clip(xpowers-1,0,None)
    newpowersy = np.clip(ypowers-1,0,None)

    newpolyorder = np.empty((2,2, 15, 2), dtype = object)
    newpolyorder[0][0] = np.stack((newpowersx,ypowers), axis = 1)
    newpolyorder[0][1] = np.stack((xpowers,newpowersy), axis = 1)
    newpolyorder[1][0] = np.stack((newpowersx,ypowers), axis = 1)
    newpolyorder[1][1] = np.stack((xpowers,newpowersy), axis = 1)

    jacob = np.empty((2,2,15), dtype = object)
    jacob[0][0] = xpowers*coefX
    jacob[0][1] = ypowers*coefX
    jacob[1][0] = xpowers*coefY
    jacob[1][1] = ypowers*coefY
    
    return jacob, newpolyorder
    
    

In [17]:
j1, poly1 = computeJacobian(0.869)

rx,ry = 0.999999999833149 0.9999999995597365


In [18]:
j2, poly2 = computeJacobian(0.48)

rx,ry = 0.9999999998202491 0.9999999995689524


In [19]:
print(len(j1[0][0]))
print(j2)

15
[[[0.0 326.51716336932896 -0.0 -0.28833334860350324 15.253881344804114
   0.0 47.28312207951724 -0.07883698151652274 16.455916685523807 0.0
   0.10747030706913423 4.980606922467922 -0.17369828752621383
   1.1353916830527422 -0.0]
  [0.0 0.0 -0.07911395242442039 -0.0 15.253881344804114
   0.01908704774780187 0.0 -0.03941849075826137 32.911833371047614
   0.03446611805742317 0.0 1.6602023074893073 -0.17369828752621383
   3.4061750491582266 -1.4843442213486457]]

 [[0.0 -0.0003893612650927025 -0.0 -15.226665314287635
   0.12715658389390022 -0.0 0.0030836663020455514 -32.8091373442911
   0.04045093619093977 -0.0 -1.2932675258147008 0.17465455556439477
   -4.2651230086788345 -0.24478192610745592 -0.0]
  [0.0 -0.0 -333.96807263502023 -0.0 0.12715658389390022
   -46.41039610172402 0.0 -16.40456867214555 0.08090187238187954
   -50.91657132795295 -0.0 0.05821818518813159 -4.2651230086788345
   -0.7343457783223677 -10.338993086875584]]]


In [20]:
poly2.shape

(2, 2, 15, 2)

In [21]:
np.shape(np.array([2,2]))

(2,)

In [22]:
np.power(np.array([2,2]), poly2)

array([[[[1, 1],
         [1, 1],
         [1, 2],
         [2, 1],
         [1, 2],
         [1, 4],
         [4, 1],
         [2, 2],
         [1, 4],
         [1, 8],
         [8, 1],
         [4, 2],
         [2, 4],
         [1, 8],
         [1, 16]],

        [[1, 1],
         [2, 1],
         [1, 1],
         [4, 1],
         [2, 1],
         [1, 2],
         [8, 1],
         [4, 1],
         [2, 2],
         [1, 4],
         [16, 1],
         [8, 1],
         [4, 2],
         [2, 4],
         [1, 8]]],


       [[[1, 1],
         [1, 1],
         [1, 2],
         [2, 1],
         [1, 2],
         [1, 4],
         [4, 1],
         [2, 2],
         [1, 4],
         [1, 8],
         [8, 1],
         [4, 2],
         [2, 4],
         [1, 8],
         [1, 16]],

        [[1, 1],
         [2, 1],
         [1, 1],
         [4, 1],
         [2, 1],
         [1, 2],
         [8, 1],
         [4, 1],
         [2, 2],
         [1, 4],
         [16, 1],
         [8, 1],
         [4, 2],
  

In [23]:
np.sum(j1*np.prod(np.power(np.array([2,2]), poly2), axis = 3), axis = 2)

array([[659.1093493139626, 192.18915741197847],
       [-206.0592997958657, -818.303622281782]], dtype=object)

In [24]:
jacob1 = evalJ(j1, poly1, -0.00522, -0.0981)

In [25]:
det = -jacob1[0][0]*jacob1[1][1]+jacob1[0][1]*jacob1[1][0]

In [27]:
np.sqrt(det)*180/np.pi

18766.917325625527